### ISSUE TITLE
Android example on how to use hoplite with buildTypes as to get different configurations for different build variants

### ISSUE THREAD

**Issue by Syrou** [sksamuel/hoplite#327]
It is not clear how to make hoplite work with different android buildTypes. A demonstration for how to make this work would be much appriciated.

**Comment by sksamuel** [comment]
What is an android buildType ?

**Comment by Syrou** [comment]
https://developer.android.com/studio/build/build-variants

Basically a way to setup staging/production builds of the android application

**Comment by sksamuel** [comment]
I know nothing about Android. Does it allow you to specify files that are included only for that build type? If so that could work. Or perhaps you could use the manifest entry to know which file to draw? Like Config.load("myconfigfile-$buildType.yml") where buildType was read from the Jar's manifest.

**Comment by Syrou** [comment]
I suppose adding an environment variable to the configuration load is one way to do it
`buildConfigField "String", "BUILD_VARIANT", "\"dev\""`
`buildConfigField "String", "BUILD_VARIANT", "\"prod\""`

and then use `Config.load("myconfigfile-$BuildConfig.BUILD_VARIANT.yml"`

**Comment by sksamuel** [comment]
Closing unless you feel more discussion is needed.
