### ISSUE TITLE
Add Decoder<IntRange>

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#37]

**Comment by fagossa** [comment]
@sksamuel I was wondering whas is the expected behaviour for `Ranges` in general? 
What is _hoplite_ should be able to deserialize from? 
e.g.
* `"1..4"` should give a `IntRange(1, 4)`?
* `"1,2,3,4"` should give a `IntRange(1, 4)`?

PS:
BTW the same question applies to the deserialization of all _ranges_

**Comment by sksamuel** [comment]
I think anything sensible. 1..4 works but 1,2,3,4 you would need to check
nothing was missing. Maybe just do 1..4

**Comment by fagossa** [comment]
I'll take this issue as well as https://github.com/sksamuel/hoplite/issues/38 and https://github.com/sksamuel/hoplite/issues/39
