### ISSUE TITLE
Option for controlling dot separate in env vars

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#77]

**Comment by Globegitter** [comment]
@sksamuel what is the idea here? Is it that I could write e.g. `server_port=8080` instead of `server.port=8080` for a nested class?

**Comment by Globegitter** [comment]
The reason I am asking btw, is because we have noticed that some shell environments only support uppercase alphanumeric characters as well as underscores. So right now I have written a custom `PropertySource` where `__` will be converted to a `.` and a single `_` is used for camel casing. So we would have `SERVER__PORT` for the example of a nested object above or e.g. `CONFIGURATION_ENDPOINTS` for a variable named `configurationEndpoints`.

**Comment by sksamuel** [comment]
Yes that's the idea as SERVER_PORT is the common way to do envs.

**Comment by sksamuel** [comment]
I've released 1.2.0 in which I've added the functionality you've suggested. So the EnvironmentVariablesPropertySource has a flag for using `__` as a `.` which it now does by default.
