### ISSUE TITLE
Hoplite can't find decoder for nullable Lists (and possibly other types)

### ISSUE THREAD

**Issue by Tmpod** [sksamuel/hoplite#96]
I came across this issue when trying to parse a config with the following structure
```kotlin
data class Foo(val bar: List<String>?, val baz: List<String>?)
```
and got 
```
- 'foo': - Could not instantiate 'a.b.c.Foo?' because:                
    - 'bar': Unable to locate a decoder for class kotlin.collections.List                
    - 'baz': Unable to locate a decoder for class kotlin.collections.List
```

Looking at the tests for the YAML module, which I'm using, I see no explicit tests for nullable Lists, so it's likely there's some issue with them that is passing.

**Comment by sksamuel** [comment]
Released 1.1.5 with fix.

**Comment by arvindbeam** [comment]
Is there any reason why classes need to be a data class and not an ordinary class for the decoder to be generated for custom types?

**Comment by sksamuel** [comment]
I suppose not, if the reflection data is available.
Why can't you use data classes ?

**Comment by arvindbeam** [comment]
No issues in using data classes at all. The error message when I used a generic class wasn't very helpful (it just said couldn't find a decoder) and it took a while before I realized the class I was using needed to be a data class. Maybe that's something that can be added - if a non-data class is found, then print that as the cause instead of saying "no decoder was found".
